name: deployment 1
on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7.0.0
      - name: install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying the project..."